2018-10-27 18:45:11,981 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:49]
2018-10-27 19:06:21,046 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:49]
2018-10-27 19:11:24,320 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:49]
2018-10-27 19:11:27,944 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:49]
2018-10-27 19:14:49,178 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:49]
2018-10-27 19:15:50,871 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:49]
2018-10-29 00:05:10,353 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:52]
2018-10-29 00:13:03,575 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 00:14:00,256 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:49:55,573 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:54:17,021 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:55:49,947 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:55:52,851 ERROR: Exception on / [GET] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/routes.py", line 46, in index
    return render_template("index.html", title='Index', script1=scrip1, div1=div1, cdn_js=cdn_js, cdn_css=cdn_css)
NameError: global name 'scrip1' is not defined
2018-10-29 22:56:02,929 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:56:46,650 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:59:12,596 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:59:23,257 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:59:26,738 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 22:59:58,349 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 23:00:25,154 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 23:01:03,698 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-29 23:01:07,488 INFO: ReDefined CRM Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/CRM/app/__init__.py:53]
2018-10-30 18:11:42,278 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:16:33,936 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:23:26,616 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:38:42,715 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:42:19,768 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:44:31,105 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:46:00,306 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:47:42,492 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:49:02,083 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:50:55,193 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:52:55,468 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:53:17,604 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:54:07,107 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 18:59:09,643 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 19:04:59,847 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 19:10:49,411 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 19:11:22,116 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 19:35:55,192 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 19:42:58,962 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 19:48:07,277 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 20:17:44,810 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 20:17:52,142 ERROR: Exception on /search_result/ts [GET] [in /mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/GM/Desktop/CRM/app/routes.py", line 68, in search_result
    searchresult=search_names(current_user, search_entry)
  File "/mnt/c/Users/GM/Desktop/CRM/app/queryfunc.py", line 84, in search_names
    client_last_names=Clients.query.filter_by(user_account_pk=account_pk).fitler(Clients.last_name.contains(search_entry)).all()
AttributeError: 'BaseQuery' object has no attribute 'fitler'
2018-10-30 20:19:09,062 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 20:19:15,924 ERROR: Exception on /search_result/ts [GET] [in /mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/GM/Desktop/CRM/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/GM/Desktop/CRM/app/routes.py", line 68, in search_result
    searchresult=search_names(current_user, search_entry)
  File "/mnt/c/Users/GM/Desktop/CRM/app/queryfunc.py", line 84, in search_names
    client_last_names=Clients.query.filter_by(user_account_pk=account_pk).fitler(Clients.last_name.contains(search_entry)).all()
AttributeError: 'BaseQuery' object has no attribute 'fitler'
2018-10-30 20:19:30,859 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 20:23:04,394 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 20:38:07,791 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
2018-10-30 20:38:45,649 INFO: ReDefined CRM Startup [in /mnt/c/Users/GM/Desktop/CRM/app/__init__.py:53]
